CC = gcc
CFLAGS = -o -Wall

urobotm: urobotm.c
	$(CC) $(CFLAGS) -o $@ $< -lm

urobot_1ch_enc_pos: urobot_1ch_enc_pos.c
	$(CC) $(CFLAGS) -o $@ $< -lm

urobot_enc_pos: urobot_enc_pos.c
	$(CC) $(CFLAGS) -o $@ $< -lm

urobotc_ad: urobotc_ad.c
	$(CC) $(CFLAGS) -o $@ $< -lm

urobotc_open_loop: urobotc_open_loop.c
	$(CC) $(CFLAGS) -o $@ $< -lm
