# Choose the Arduino board
BOARD_TAG     		= mega2560

# Set the Serial port 
MONITOR_PORT  		= /dev/ttyACM0

# Set the Baudrate
MONITOR_BAUDRATE 	= 115200

# 独自のライブラリの追加
ARDUINO_LIBS    += ros_lib

# Include Arduino.mk
include /usr/share/arduino/Arduino.mk
